force-app/main/default/objects/Tweet__c/Tweet__c.object-meta.xml
<CustomObject>
    <description>Tweets custom object for Twitter Integration App</description>
    <label>Tweet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tweet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tweets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tweet__c/fields/Reply_Count__c.field-meta.xml
<CustomField>
    <fullName>Reply_Count__c</fullName>
    <label>Reply Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/Retweet_Count__c.field-meta.xml
<CustomField>
    <fullName>Retweet_Count__c</fullName>
    <label>Retweet Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>Text area for Tweet</description>
    <label>Text</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/Tweet_Id__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Id__c</fullName>
    <externalId>true</externalId>
    <label>Tweet Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {
    
    public static void generate() {
        TwitterUser tu = TwitterUser.parse();
        List<Tweet__c> tweets = new List<Tweet__c>();
        for(TwitterUser.cls_data data:tu.data){
            Tweet__c tweet = new Tweet__c();
            tweet.Likes__c = data.public_metrics.like_count;
            tweet.Retweet_Count__c = data.public_metrics.retweet_count;
            tweet.Reply_Count__c = data.public_metrics.reply_count;
            tweet.Text__c = data.text;
            tweet.Tweet_Id__c = data.id;
            tweet.Created_At__c = datetime.valueOf(data.created_at);
            tweets.add(tweet);
        }
        upsert tweets Tweet_Id__c;
        
    }
    
}